filter:
    excluded_paths: [vendor/*, tests/*]

tools:
    php_cpd:
        excluded_dirs: [vendor, tests]

    php_pdepend:
        excluded_dirs: [vendor, tests]

    php_analyzer: true

    js_hint: true
