language: php

php:
  - "5.5"
  - "5.4"
  - "5.3"

services:
  - mysql
  - memcached
  - elasticsearch
  - redis-server

before_script:
  - pecl install runkit
  - sh -c "if [ `php-config --vernum` -ge 50500 ]; echo "yes" | pecl install apcu-beta; fi"
  - phpenv config-add tests/travis/php-$TRAVIS_PHP_VERSION.ini

  - composer self-update
  - composer install --dev
  - scripts/cm.php app generate-config-local tests/travis/config.json
  - scripts/cm.php app set-deploy-version

script: phpunit

notifications:
  email: false
